//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWithAuthenticationTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class jobEntities1 : DbContext
    {
        public jobEntities1()
            : base("name=jobEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<CompanyOffer> CompanyOffer { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Programador> Programador { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
