//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWithAuthenticationTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Programador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Programador()
        {
            this.Language = new HashSet<Language>();
        }
    
        public string ProgramadorGUID { get; set; }

        public int ProgramadorID { get; set; }
        [Display(Name = "Primeiro nome")]
        public string FirstName { get; set; }
        [Display(Name = "Apelido")]
        public string LastName { get; set; }
        [Display(Name = "Correio eletronico")]
        public string Email { get; set; }
        [Display(Name = "Senha")]
        public string Password { get; set; }
        [Display(Name = "Idade")]
        public Nullable<int> Age { get; set; }
        [Display(Name = "Contacto telefonico")]
        public string PhoneNumber { get; set; }
        [Display(Name = "Localidade")]
        public string Location { get; set; }
        [Display(Name = "Posicao atual")]
        public string Category { get; set; }
        [Display(Name = "Descricao")]
        public string Description { get; set; }
        [Display(Name = "Preco por hora")]
        public Nullable<double> Price_hour { get; set; }
        [Display(Name = "Fotografia de perfil")]
        public string Foto { get; set; }
        [Display(Name = "Link para o GitHub")]
        public string LinkGithub { get; set; }
        [Display(Name = "Link para o Linkedin")]
        public string LinkLinkedin { get; set; }
        [Display(Name = "Certificados")]
        public string Certificates { get; set; }
        [Display(Name = "Perfil privado?")]
        public Nullable<bool> Privacy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Language> Language { get; set; }
    }
}
